config/Config-template.groovy

In favour to spring-security-core.properties that is located inside web app.
Merge this PR just after https://github.com/transmart/transmartApp/pull/103.

Delete custom spring security messages.

---

data/common/searchapp/plugin_modules_params/plugin_module-template.tsv

Remove Forest Plot from list of available analysis

---

config/Config-extra.php.sample

This regex is used by "Change My Password" functionality.

Regex to validate strength of user password.

---

ddl/oracle/i2b2demodata/_cross.sql
ddl/postgres/i2b2demodata/_cross.sql

CONCEPT_ID sequence doesn't exist in tm_cz but i2b2_demodata

fixed wrong schema qualification in concept_domain insert trigger

---

ddl/oracle/deapp/views/de_variant_summary_detail_gene.sql
ddl/postgres/deapp/views/de_variant_summary_detail_gene.sql

to support changes in https://github.com/transmart/transmart-core-db/commit/633b84b74a6cb9a76f418a5f050c7a2afc0d0323

Include rs_id in join condition

---

env/Makefile

target "update_etl" should use repository "tranSMART-ETL" from tranSMART-foundation instead of outdated "transmart-ETL" from TheHyve

Update Makefile (from "env" directory)

---

config/Config-template.groovy

Reverts transmart/transmart-data#79

Revert "Support upgrade of oauth2 module"

---

env/Makefile

Use https: instead of git: protocol

---

ddl/postgres/tm_cz/functions/i2b2_process_rnaseq_data.sql
samples/common/load_expression.sh
samples/common/process_params.inc
samples/postgres/load_chromosomal_region_annotation.sh
samples/postgres/load_rnaseq.sh
vars.sample

@forus This pull request addresses several (minor) issues related to the loading process of molecular data. Also some extra consistency checks in the loading scripts are introduced.

various small (robustness) improvements and bug fixes

---

env/Makefile
lib/makefile.inc
solr/Makefile

Another go at hacking makefiles. 
See also #99

Automatically download Oracle JDBC driver for Kettle

---

ddl/oracle/grants.php

ts db user has to have access to the amapp views

Fix db permissions for Browse tab.

---

samples/studies/public-feeds

Has a copy of the data on the old (Postgres ETL test) server

point to transmart demo server - uses port 80

---

ddl/postgres/tm_cz/functions/i2b2_backout_trial.sql
ddl/postgres/tm_cz/functions/i2b2_process_rnaseq_data.sql
samples/common/load_expression.sh
samples/common/process_params.inc
samples/postgres/load_chromosomal_region_annotation.sh
samples/postgres/load_rnaseq.sh

@forus This pull request addresses several (minor) issues related to the loading process of molecular data.
- Some extra consistency checks in the loading scripts are introduced.
- Update of RNASeq data loading script to support loading of normalized readcounts as well as log2 normalized readcounts
- Update of i2b2_backout_trial stored procedure to ensure that all partition tables are dropped (in case a study contains more than one molecular dataset of the same type

modifications to increase robustness of data loading

---

samples/common/load_expression.sh
samples/postgres/load_annotation.sh
samples/postgres/load_chromosomal_region_annotation.sh
samples/postgres/load_rnaseq.sh

Spaces in file-names during data-upload should be possible now.

FT-1732 space in filenames

---

config/Config-template.groovy

We now can configure the maximum number of concurrent
user sessions allowed.
See pull request #173 on transmart/transmartApp

FT-1550 Concurrent Users-session

---

config/Config-template.groovy

Add slash when address is composed instead.

Keep url wo slash at the end.

---

ddl/oracle/tm_cz/procedures/i2b2_process_mrna_data.sql
ddl/postgres/tm_cz/functions/i2b2_process_mrna_data.sql

Cache could contain stale information.

Use production platform table instead of cache.

---

README.md

Via HipChat - Gustavo states that this tag was removed "long ago".

Removed reference to Analysis tag in data-loading

---

samples/common/makefile.inc

Pass STUDY_ID (required parameter)

Fix data upload with transmart batch.

---

config/Config-template.groovy

Use `ui.loginScreen.disclaimer` in the config file to specify the disclaimer message.
Related PR: https://github.com/transmart/transmartApp/pull/189

Add commented disclaimer msg to the config file.

---

R/other_pkg.R

For plotting a chromosomal-axis based on base-pairs we need R-library QDNAseq (bioConductor).

FT-1821-Fix_accordeon_chromosomes.

---

config/Config-template.groovy

Update configuration generation of URL mappings, logging and application version.

Update configuration for 17.1
